using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Movies.WinRT.Models;
using Windows.Foundation;

namespace Movies.WinRT.Repositories
{
    public class MovieRepository : IMovieRepository
    {
        public IEnumerable<Movie> LoadMovies()
        {
			var movies = new List<Movie>();

			var id = 1;
			movies.Add(new Movie(id++, "The Dark Knight Rises", Genres.Action, Ratings.PG13, "/Posters/The-Dark-Knight-Rises.jpg", "It has been eight years since Batman vanished into the night, turning, in that instant, from hero to fugitive. Assuming the blame for the death of D.A. Harvey Dent, the Dark Knight sacrificed everything for what he and Commissioner Gordon both hoped was the greater good. For a time the lie worked, as criminal activity in Gotham City was crushed under the weight of the anti-crime Dent Act. But everything will change with the arrival of a cunning cat burglar with a mysterious agenda. Far more  dangerous, however, is the emergence of Bane, a masked terrorist whose ruthless plans for Gotham drive Bruce out of his self-imposed exile. But even if he dons the cape and cowl again, Batman may be no match for Bane."));
			movies.Add(new Movie(id++, "The Hangover Part 2", Genres.Comedy, Ratings.R, "/Posters/The-Hangover-Part-2.jpg", "In The Hangover Part II, Phil (Bradley Cooper), Stu (Ed Helms), Alan (Zach Galifianakis) and Doug (Justin Bartha) travel to exotic Thailand for Stu's wedding. After the unforgettable bachelor party in Las Vegas, Stu is taking no chances and has opted for a safe, subdued pre-wedding brunch. However, things don't always go as planned. What happens in Vegas may stay in Vegas, but what happens in Bangkok can't even be imagined."));
			movies.Add(new Movie(id++, "Prometheus", Genres.SciFi, Ratings.R, "/Posters/Prometheus.jpg", "Ridley Scott, director of Alien and Blade Runner, returns to the genre he helped define. With Prometheus, he creates a groundbreaking mythology, in which a team of explorers discover a clue to the origins of mankind on Earth, leading them on a thrilling journey to the darkest corners of the universe. There, they must fight a terrifying battle to save the future of the human race."));
			movies.Add(new Movie(id++, "The Expendables 2", Genres.Action, Ratings.R, "/Posters/The-Expendables-2.jpg", "The Expendables are back and this time it's personal... Barney Ross (Sylvester Stallone), Lee Christmas (Jason Statham), Yin Yang (Jet Li), Gunnar Jensen (Dolph Lundgren),Toll Road (Randy Couture) and Hale Caesar (Terry Crews) -- with newest members Billy the Kid (Liam Hemsworth) and Maggie (Yu Nan) aboard -- are reunited when Mr. Church (Bruce Willis) enlists the Expendables to take on a seemingly simple job. The task looks like an easy paycheck for Barney and his band of old-school  mercenaries. But when things go wrong and one of their own is viciously killed, the Expendables are compelled to seek revenge in hostile territory where the odds are stacked against them."));
			movies.Add(new Movie(id++, "Finding Nemo 3D", Genres.Adventure, Ratings.G, "/Posters/Finding-Nemo-3D.jpg", "In this stunning underwater adventure, with memorable characters, humor and heartfelt emotion, Finding Nemo follows the comedic and momentous journey of an overly protective clownfish named Marlin (voice by Albert Brooks) and his son Nemo (voice by Alexander Gould) -- who become separated in the Great Barrier Reef when Nemo is unexpectedly taken far from his ocean home and dumped into a fish tank in a dentist's office. Buoyed by the companionship of Dory (voice by Ellen DeGeneres), a  friendly-but-forgetful Pacific regal blue tang, Marlin embarks on a dangerous trek and finds himself the unlikely hero of an epic effort to rescue his son -- who hatches a few daring plans of his own to return safely home."));
			movies.Add(new Movie(id++, "Act Of Valor", Genres.Action, Ratings.R, "/Posters/Act-Of-Valor.jpg", "An unprecedented blend of real-life heroism and original filmmaking, Act of Valor stars a group of active-duty U.S. Navy SEALs in a film like no other in Hollywood's history. A fictionalized account of real life Navy SEAL operations, Act of Valor features a gripping story that takes audiences on an adrenaline-fueled, edge-of-their-seat journey. When a mission to recover a kidnapped CIA operative unexpectedly results in the discovery of an imminent, terrifying global threat, an elite team of  highly trained Navy SEALs must immediately embark on a heart-stopping secret operation, the outcome of which will determine the fate of us all. Act of Valor combines stunning combat sequences, up-to-the-minute battlefield technology, and heart-pumping emotion for the ultimate action adventure film-showcasing the skills, training and tenacity of the greatest action heroes of them all: real Navy SEALs."));
			movies.Add(new Movie(id++, "The Hunger Games", Genres.Adventure, Ratings.PG13, "/Posters/The-Hunger-Games.jpg", "Every year in the ruins of what was once North America, the evil Capitol of the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games. A twisted punishment for a past uprising and an ongoing government intimidation tactic, The Hunger Games are a nationally televised event in which \"Tributes\" must fight with one another until one survivor remains. Pitted against highly-trained Tributes who have prepared for these Games their entire  lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy. If she's ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love."));
			movies.Add(new Movie(id++, "The Avengers", Genres.Action, Ratings.PG13, "/Posters/The-Avengers.jpg", "Marvel Studios presents Marvel's The Avengers-the Super Hero team up of a lifetime, featuring iconic Marvel Super Heroes Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When an unexpected enemy emerges that threatens global safety and security, Nick Fury, Director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins."));
			movies.Add(new Movie(id++, "Men In Black 3", Genres.Comedy, Ratings.PG13, "/Posters/Men-In-Black-3.jpg", "In Men in Black 3, Agents J (Will Smith) and K (Tommy Lee Jones) are back...in time. J has seen some inexplicable things in his 15 years with the Men in Black, but nothing, not even aliens, perplexes him as much as his wry, reticent partner. But when K's life and the fate of the planet are put at stake, Agent J will have to travel back in time to put things right. J discovers that there are secrets to the universe that K never told him -- secrets that will reveal themselves as he teams up with  the young Agent K (Josh Brolin) to save his partner, the agency, and the future of humankind."));
			movies.Add(new Movie(id++, "Ted", Genres.Comedy, Ratings.R, "/Posters/Ted.jpg", "Family Guy creator Seth MacFarlane brings his boundary-pushing brand of humor to the big screen for the first time as writer, director and voice star of Ted. In the live action/CG-animated comedy, he tells the story of John Bennett (Mark Wahlberg), a grown man who must deal with the cherished teddy bear who came to life as the result of a childhood wish...and has refused to leave his side ever since."));
			movies.Add(new Movie(id++, "The Campaign", Genres.Comedy, Ratings.R, "/Posters/The-Campaign.jpg", "When long-term congressman Cam Brady (Will Ferrell) commits a major public gaffe before an upcoming election, a pair of ultra-wealthy CEOs plot to put up a rival candidate and gain influence over their North Carolina district. Their man: naïve Marty Huggins (Zach Galifianakis), director of the local Tourism Center. At first, Marty appears to be the unlikeliest possible choice but, with the help of his new benefactors' support, a cutthroat campaign manager and his family's political connections,  he soon becomes a contender who gives the charismatic Cam plenty to worry about. As Election Day closes in, the two are locked in a dead heat, with insults quickly escalating to injury until all they care about is burying each other, in this mud-slinging, back-stabbing, home-wrecking comedy."));
			movies.Add(new Movie(id++, "Looper", Genres.SciFi, Ratings.R, "/Posters/Looper.jpg", "In the futuristic action thriller Looper, time travel will be invented - but it will be illegal and only available on the black market. When the mob wants to get rid of someone, they will send their target 30 years into the past, where a \"looper\" - a hired gun, like Joe (Joseph Gordon-Levitt) - is waiting to mop up. Joe is getting rich and life is good... until the day the mob decides to \"close the loop,\" sending back Joe's future self (Bruce Willis) for assassination."));

			return movies;
        }


		public IEnumerable<Movie> LoadMoviesByGroup(string groupName)
		{
			var movies = LoadMovies();

			return movies.Where(m => m.Genre.ToString() == groupName);
		}
	}
}
